SELECT * FROM KMS_Stock

 SELECT * FROM KMS_Stock Returned_Order

---Which product category had the highest sales?

SELECT TOP 1 PRODUCT_CATEGORY, 
SUM(SALES) AS HIGHEST_SALES
FROM KMS_Stock
GROUP BY PRODUCT_CATEGORY
ORDER BY HIGHEST_SALES desc

---What are the Top 3 and Bottom 3 regions in terms of sales?

---TOP 3 REGIONS IN TERMS OF SALES

SELECT TOP 3  REGION,
SUM(SALES) AS HIGHEST_REGION_SALES
FROM KMS_Stock
GROUP BY REGION
ORDER BY HIGHEST_REGION_SALES DESC

-----BOTTOM 3 REGIONS IN TERMS OF SALES

SELECT TOP 3 REGION, 
SUM (SALES) AS LOWEST_REGION_SALES
FROM KMS_Stock
GROUP BY REGION
ORDER BY LOWEST_REGION_SALES ASC

---What were the total sales of appliances in Ontario?

SELECT SUM(SALES) AS TOTAL_ONTARIO_APPLIANCES_SALES
FROM KMS_Stock
WHERE PRODUCT_SUB_CATEGORY = 'APPLIANCES' AND REGION = 'ONTARIO'

---Advise the management of KMS on what to do to increase the revenue from the bottom
---10 customers

SELECT TOP 10 CUSTOMER_NAME, 
SUM (SALES) AS LOWEST_CUSTOMER_SALES, 
SUM(PROFIT) AS TOTAL_PROFIT,
SUM (SHIPPING_COST) AS TOTAL_SHIPPING_COST, 
SUM(DISCOUNT) AS TOTAL_DISCOUNT, 
COUNT(ORDER_ID) AS TOTAL_ORDER
FROM KMS_Stock
GROUP BY CUSTOMER_NAME
ORDER BY LOWEST_CUSTOMER_SALES ASC

---KMS incurred the most shipping cost using which shipping method?

SELECT TOP 1 SHIP_MODE, 
SUM(SHIPPING_COST) AS HIGHEST_SHIPPING_MODE
FROM KMS_Stock
GROUP BY SHIP_MODE
ORDER BY HIGHEST_SHIPPING_MODE DESC

---Who are the most valuable customers, and what products or services do they typically
---purchase?

SELECT TOP 10 CUSTOMER_NAME, 
PRODUCT_NAME, SUM(SALES) AS TOP_CUSTOMERS,
SUM (Profit) AS TOTAL_PROFIT
FROM KMS_Stock
GROUP BY CUSTOMER_NAME, PRODUCT_NAME
ORDER BY TOP_CUSTOMERS DESC

---Which small business customer had the highest sales?

SELECT TOP 1 CUSTOMER_NAME, CUSTOMER_SEGMENT,  
SUM(SALES) AS SMALL_BUSINESS_HIGHEST_SALES
FROM  KMS_Stock
WHERE CUSTOMER_SEGMENT = 'SMALL BUSINESS'
GROUP BY CUSTOMER_NAME, CUSTOMER_SEGMENT
ORDER BY SMALL_BUSINESS_HIGHEST_SALES DESC

---Which Corporate Customer placed the most number of orders in 2009 – 2012

SELECT TOP 1 CUSTOMER_NAME, CUSTOMER_SEGMENT, 
COUNT (ORDER_ID) AS MOST_ORDER
FROM KMS_Stock
WHERE CUSTOMER_SEGMENT = 'CORPORATE' AND ORDER_DATE >= '2009-01-01' AND ORDER_DATE <= '2012-12-31'
GROUP BY CUSTOMER_NAME, CUSTOMER_SEGMENT
ORDER BY MOST_ORDER DESC

---Which consumer customer was the most profitable one?

SELECT TOP 1 CUSTOMER_NAME, CUSTOMER_SEGMENT, 
SUM(PROFIT) AS CONSUMER_CUSTOMER_MOST_PPROFITABLE
FROM KMS_Stock
WHERE CUSTOMER_SEGMENT = 'CONSUMER'
GROUP BY CUSTOMER_NAME, CUSTOMER_SEGMENT
ORDER BY CONSUMER_CUSTOMER_MOST_PPROFITABLE DESC

---Which customer returned items, and what segment do they belong to?

 CREATE VIEW KMS_Stock_View
 AS  
SELECT KMS_Stock.ORDER_ID, 
KMS_Stock.SALES,  
KMS_Stock.CUSTOMER_NAME, 
KMS_Stock.CUSTOMER_SEGMENT, 
Order_Status.[Status]
FROM KMS_Stock
FULL OUTER JOIN Order_Status
ON KMS_Stock.Order_ID = Order_Status.Order_ID

select * from KMS_Stock_VIEW

SELECT DISTINCT CUSTOMER_NAME, CUSTOMER_SEGMENT, [STATUS]
FROM KMS_Stock_VIEW
WHERE [STATUS] = 'RETURNED'

---If the delivery truck is the most economical but the slowest shipping method and
---Express Air is the fastest but the most expensive one, do you think the company
---appropriately spent shipping costs based on the Order Priority? Explain your answer

SELECT SHIP_MODE, ORDER_PRIORITY,
SUM(SHIPPING_COST) AS TOTAL_SHIPPING_COST,
Avg(Shipping_Cost) AS Average_Shipping_Cost
FROM KMS_Stock
WHERE Ship_Mode IN ('Express Air', 'Delivery Truck')
GROUP BY ORDER_PRIORITY, SHIP_MODE
ORDER BY ORDER_PRIORITY, SHIP_MODE

---NO, I DON'T THINK SO. SINCE EXPRESS IS THE FASTEST AND THE MOST EXPENSIVE, 
---IT SHOULD BE USED FOR TRANSPORTING CRITICAL AND HIGH ORDERS WHILE TRUCKS SHOULD BE USE for TRANSPORT
---LOW, MEDIUM AND NOT SPECIFIED ORDERS.












